server:
 port: 12000
spring:
 application:
  name: goods-page
 rabbitmq:
  host: 172.23.35.155
  username: ego
  password: ego
  virtual-host: /ego
  template:
   exchange: ego.item.exchange
thymeleaf:
 cache: false
 main:
  allow-bean-definition-overriding: true
eureka:
 client:
  service-url:
   defaultZone: http://@eureka1:7001/eureka
 instance:
  lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
  lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
  prefer-ip-address: true
  ip-address: 127.0.0.1
  instance-id: ${spring.application.name}.${server.port}