server:
 port: 8050
spring:
 rabbitmq:
  host: 172.23.35.155
  username: ego
  password: ego
  virtual-host: /ego
  template:
   exchange: ego.item.exchange
  publisher-confirms: true
 jackson:
  default-property-inclusion: non_null # 配置json处理时忽略空值
 application:
  name: search-service
 data:
  elasticsearch:
   cluster-name: elasticsearch
   cluster-nodes: 172.23.35.155:9300
eureka:
 client:
  service-url:
   defaultZone: http://@eureka1:7001/eureka
 instance:
  lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
  lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
  prefer-ip-address: true
  ip-address: 127.0.0.1
  instance-id: ${spring.application.name}:${server.port}
ribbon:
 eureka:
  enabled=true: