server:
 port: 10001
spring:
 application:
  name: api-gateway
 main:
  allow-bean-definition-overriding: true
eureka:
 client:
  service-url:
   defaultZone: http://@eureka1:7001/eureka
  registry-fetch-interval-seconds: 5
 instance:
  prefer-ip-address: true
  ip-address: 127.0.0.1
  instance-id: ${spring.application.name}:${server.port}
  hostname: zuul1
zuul:
 prefix: /api # 添加路由前缀
 retryable: true
 routes:
  item-service: /item/**
  search-service: /search/**
  user-service: /user/**
  auth-service: /auth/**
  cart-service: /cart/**
  order-service: /order/**
  seckill-service: /seckill/**
 ignored-services: upload-service      #zuul关闭上传文件服务
 add-host-header: true     #携带请求真是host
 sensitive-headers:  #不要过滤任何响应头
#  upload-service: /upload/**
ribbon:
 ConnectTimeout: 250 # 连接超时时间(ms)
 ReadTimeout: 2000 # 通信超时时间(ms)
 OkToRetryOnAllOperations: true # 是否对所有操作重试
 MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
 MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMillisecond: 100000 # 熔断超时时长：10000ms
ego:
 filter:
  pref: http://api.ego.com
  allowPaths:
   - /api/auth
   - /api/search
   - /api/user/register
   - /api/user/check
   - /api/user/code
   - /api/item
 jwt:
  pubKeyPath: D:\\JetBrains\\rsa\\rsa.pub # 公钥地址
  cookieName: EGO_TOKEN