server:
 port: 14000
spring:
 redis:
  host: 127.0.0.1
 application:
  name: user-service
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/ego?useUnicode=true&characterEncoding=utf8
  username: root
  password: root
  driver-class-name: com.mysql.jdbc.Driver
 rabbitmq:
  virtual-host: /ego
  host: 172.23.35.155
  username: ego
  password: ego
  template:
   exchange: ego.sms.exchange
  publisher-confirms: true
eureka:
 client:
  service-url:
   defaultZone: http://@eureka1:7001/eureka
 instance:
  prefer-ip-address: true
  ip-address: 127.0.0.1
  instance-id: ${eureka.instance.ip-address}.${server.port}
  lease-renewal-interval-in-seconds: 5
  lease-expiration-duration-in-seconds: 15
mybatis:
 type-aliases-package: com.ego.user.pojo
